# Generated by Django 2.0.1 on 2018-08-31 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_word', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('cid', models.IntegerField()),
                ('tags', models.CharField(max_length=255)),
                ('create_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50)),
                ('create_at', models.DateTimeField()),
            ],
        ),
    ]
